### ISSUE TITLE
Zeros store negative 

### ISSUE THREAD

**Issue by karasjoh000** [dnsl48/fraction#12]
Not sure if it is intended but zeros store negatives inside. When I print a zero fraction I get `-0`.

**Comment by karasjoh000** [comment]
not all zeros but I think after a number turns into a `0` from a negative on one of the Ops.

**Comment by karasjoh000** [comment]
Although if it returns equals on `-0` and `0` it should be fine. Did not have time to check yet.

**Comment by dnsl48** [comment]
yes, that's been intentional so far. We even have a separate method `Fraction::neg_zero()`.

However, now I'm contemplating the actual benefits of having negative zeroes. Rust core float implementation does handle negative zeroes and zeroes as the same thing, so do we to be compatible. I'm not sure we need this any more. Perhaps worth deprecating and removing them.

**Comment by dnsl48** [comment]
> Although if it returns equals on -0 and 0 it should be fine. Did not have time to check yet.

Yes, they are equals. We have it covered with tests
https://github.com/dnsl48/fraction/blob/master/src/fraction/mod.rs#L2746

If you have any other questions or recommendations that we can consider when deciding on if it's worth deprecating negative zeroes and removing those, please feel free to leave them here and reopen or make a new issue.

Cheers
