### ISSUE TITLE
panic: attempt to multiply with overflow

### ISSUE THREAD

**Issue by lovebug356** [dnsl48/fraction#15]
I get a panic when I run the following code (with fraction=0.6.2):
```rust
use fraction::Decimal;

fn main() {
    let d1 = Decimal::from("0.0002") * Decimal::from("9876.54321");
    let d2 = Decimal::from("51.53023471399515");
    let d3 = d1 + d2;

    println!("{:?} + {:?} = {:?}", d1, d2, d3);
}
```

```bash
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/fraction-test`
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/arith.rs:318:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by dnsl48** [comment]
Hi @lovebug356. Yes, by default there's no overflow checks performed so that there are no performance penalties for when it's not required.
If you expect there may be huge numbers, you can try either of these 
  - [BigDecimal](https://docs.rs/fraction/0.6.2/fraction/prelude/type.BigDecimal.html) - always allocates as much memory as necessary for the computations, but uses heap
  - [DynaDecimal](https://docs.rs/fraction/0.6.2/fraction/prelude/type.DynaDecimal.html) - uses stack by default, but performs overflow checks and allocates on heap if more memory is required

**Comment by dnsl48** [comment]
If it doesn't solve your issue or you have any other questions, please feel free to reopen this issue or create a new on.

**Comment by lovebug356** [comment]
Thanks for the feedback! I will try the other types.
